'use client'

import { useMemo, useState } from 'react'
import { AlertTriangle, CheckCircle2, Regex, RotateCcw, Trash2 } from 'lucide-react'
import { analyzeRegex, countLines, MAX_REGEX_INPUT_LENGTH, REGEX_PRESETS, type RegexPreset } from '@/lib/regex-utils'

const FLAG_OPTIONS = [['g', 'Global'], ['i', 'Ignore case'], ['m', 'Multiline'], ['s', 'Dotall'], ['u', 'Unicode']] as const

export function RegexTester({ embeddedInAnalysisLab = false }: { embeddedInAnalysisLab?: boolean }) {
  const [pattern, setPattern] = useState('\\b(?:error|failed|denied)\\b')
  const [input, setInput] = useState('2026-10-07 10:14:22 ERROR authentication failed\n2026-10-07 10:15:01 INFO session accepted\n2026-10-07 10:16:48 access denied for analyst@example.com')
  const [flags, setFlags] = useState('gi')
  const analysis = useMemo(() => analyzeRegex(pattern, input, flags), [pattern, input, flags])
  const captureCount = analysis.matches[0]?.groups.length ?? 0
  const hasPattern = pattern.trim().length > 0

  function applyPreset(name: RegexPreset) { setPattern(REGEX_PRESETS[name].pattern); setFlags(REGEX_PRESETS[name].flags) }
  function toggleFlag(flag: string) { setFlags((current) => current.includes(flag) ? current.replace(flag, '') : current + flag) }
  function clearAll() { setPattern(''); setInput(''); setFlags('g') }

  return <main className={embeddedInAnalysisLab ? 'w-full pt-4 pb-6' : 'mx-auto max-w-[1500px] px-4 py-6 sm:px-6 lg:px-8'}>
    <header className="mb-5 border-b border-white/[0.08] pb-5">
      <p className="inline-flex items-center gap-2 font-mono text-[10px] uppercase tracking-[0.2em] text-cyan-300"><Regex className="size-4" /> MATCH EXPRESSION</p>
      <div className="mt-3 flex flex-wrap items-start justify-between gap-4">
        <div><h1 className="text-2xl font-semibold tracking-tight text-white sm:text-3xl">Regex Tester &amp; Pattern Analyzer</h1><p className="mt-2 max-w-2xl text-sm text-slate-400">Test expressions against analyst text, inspect matches, and review capture groups without leaving the browser.</p></div>
        <span className="inline-flex items-center gap-2 rounded border border-emerald-400/25 bg-emerald-400/10 px-3 py-1.5 font-mono text-[10px] uppercase tracking-wider text-emerald-300"><span className="size-1.5 rounded-full bg-emerald-400" /> Client-side only</span>
      </div>
    </header>

    <div className="grid items-stretch gap-4 lg:grid-cols-2">
      <section className="flex min-h-[450px] flex-col rounded-xl border border-white/[0.1] bg-[#0d121c] p-4 sm:p-5">
        <div className="flex items-center justify-between gap-3"><h2 className="font-mono text-xs font-semibold uppercase tracking-[0.16em] text-cyan-300">Regex Pattern</h2><button type="button" onClick={() => { setPattern(''); setFlags('g') }} className="inline-flex items-center gap-1.5 text-[11px] text-slate-500 hover:text-cyan-300"><RotateCcw className="size-3.5" /> Reset</button></div>
        <label htmlFor="regex-pattern" className="sr-only">Regex pattern</label><textarea id="regex-pattern" value={pattern} onChange={(event) => setPattern(event.target.value)} spellCheck={false} className="mt-4 min-h-28 w-full resize-y rounded-lg border border-white/[0.1] bg-[#080c13] p-3 font-mono text-sm text-slate-200 outline-none focus:border-cyan-400/60 focus:ring-1 focus:ring-cyan-400/30" placeholder="Enter a regular expression" />
        <div className="mt-4"><p className="mb-2 font-mono text-[10px] uppercase tracking-wider text-slate-500">Presets</p><div className="flex flex-wrap gap-2">{(Object.keys(REGEX_PRESETS) as RegexPreset[]).map((name) => <button key={name} type="button" onClick={() => applyPreset(name)} className="rounded border border-white/[0.1] px-2.5 py-1.5 font-mono text-[11px] text-slate-400 hover:border-cyan-400/50 hover:text-cyan-300">{name}</button>)}</div></div>
        <fieldset className="mt-5"><legend className="mb-2 font-mono text-[10px] uppercase tracking-wider text-slate-500">Regex flags</legend><div className="flex flex-wrap gap-2">{FLAG_OPTIONS.map(([flag, label]) => <label key={flag} className={`inline-flex cursor-pointer items-center gap-1.5 rounded border px-2.5 py-1.5 font-mono text-[11px] ${flags.includes(flag) ? 'border-cyan-400/50 bg-cyan-400/10 text-cyan-300' : 'border-white/[0.1] text-slate-500'}`}><input type="checkbox" checked={flags.includes(flag)} onChange={() => toggleFlag(flag)} className="sr-only" />{flag} <span className="font-sans text-[10px]">— {label}</span></label>)}</div></fieldset>
        <div className="mt-auto grid grid-cols-2 gap-3 border-t border-white/[0.08] pt-4 font-mono text-[11px] text-slate-500"><span>Pattern length <strong className="text-slate-300">{pattern.length}</strong></span><span>Active flags <strong className="text-cyan-300">{flags || 'none'}</strong></span></div>
      </section>

      <section className="flex min-h-[450px] flex-col rounded-xl border border-white/[0.1] bg-[#0d121c] p-4 sm:p-5"><div className="flex items-center justify-between gap-3"><h2 className="font-mono text-xs font-semibold uppercase tracking-[0.16em] text-cyan-300">Test Input</h2><button type="button" onClick={() => setInput('')} className="inline-flex items-center gap-1.5 text-[11px] text-slate-500 hover:text-cyan-300"><Trash2 className="size-3.5" /> Clear</button></div><label htmlFor="regex-input" className="sr-only">Test input</label><textarea id="regex-input" value={input} maxLength={MAX_REGEX_INPUT_LENGTH} onChange={(event) => setInput(event.target.value)} spellCheck={false} className="mt-4 min-h-[310px] flex-1 resize-none overflow-auto rounded-lg border border-white/[0.1] bg-[#080c13] p-3 font-mono text-sm leading-6 text-slate-200 outline-none focus:border-cyan-400/60 focus:ring-1 focus:ring-cyan-400/30" placeholder="Paste logs or plain text to test" /><div className="mt-4 flex justify-between border-t border-white/[0.08] pt-4 font-mono text-[11px] text-slate-500"><span>Characters <strong className="text-slate-300">{input.length.toLocaleString()}</strong></span><span>Lines <strong className="text-slate-300">{countLines(input)}</strong></span></div></section>
    </div>

    <section className="mt-4 rounded-xl border border-white/[0.1] bg-[#0d121c] p-4 sm:p-5"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-white/[0.08] pb-4"><div><h2 className="font-mono text-xs font-semibold uppercase tracking-[0.16em] text-cyan-300">Match Results</h2><p className="mt-1 font-mono text-[11px] text-slate-500">{analysis.error ? 'Pattern validation failed' : !hasPattern ? 'No pattern entered' : `${analysis.matches.length} match${analysis.matches.length === 1 ? '' : 'es'} found`}</p></div>{analysis.error ? <span className="inline-flex items-center gap-1.5 rounded border border-rose-400/30 bg-rose-400/10 px-2.5 py-1 font-mono text-[11px] text-rose-300"><AlertTriangle className="size-3.5" /> Invalid pattern</span> : <span className="inline-flex items-center gap-1.5 rounded border border-emerald-400/25 bg-emerald-400/10 px-2.5 py-1 font-mono text-[11px] text-emerald-300"><CheckCircle2 className="size-3.5" /> {analysis.matches.length} matches found</span>}</div>{analysis.error ? <p role="alert" className="mt-5 rounded-lg border border-rose-400/20 bg-rose-400/[0.06] p-4 font-mono text-xs text-rose-200">{analysis.error}</p> : analysis.matches.length === 0 ? <div className="py-12 text-center font-mono text-sm text-slate-500">{!hasPattern ? <><p>No pattern entered</p><p className="mt-2 text-xs">Enter a regular expression to begin testing.</p></> : 'No matches found. Adjust the pattern or test input.'}</div> : <div className="mt-4 max-h-96 overflow-auto"><div className="min-w-[700px] divide-y divide-white/[0.06]">{analysis.matches.map((match, index) => <article key={`${match.index}-${index}`} className="grid grid-cols-[32px_minmax(140px,1fr)_180px_minmax(180px,1.5fr)] items-center gap-3 py-3 font-mono text-xs"><span className="text-slate-600">{index + 1}</span><code className="truncate text-cyan-200">{match.value || '(empty)'}</code><span className="text-slate-400">Line {match.line} · Pos {match.column}–{match.endColumn}</span><span className="truncate text-slate-500" title={match.context}>{match.context}</span></article>)}</div></div>}{!analysis.error && analysis.matches.length > 0 && <details className="mt-4 border-t border-white/[0.08] pt-4"><summary className="cursor-pointer font-mono text-[11px] uppercase tracking-wider text-slate-400 hover:text-cyan-300">Capture Groups ({captureCount})</summary><div className="mt-3 grid max-h-64 gap-2 overflow-auto sm:grid-cols-2">{analysis.matches.map((match, index) => <div key={`groups-${index}`} className="rounded border border-white/[0.08] bg-[#080c13] p-3 font-mono text-[11px]"><span className="text-slate-500">Match {index + 1}</span>{match.groups.length ? match.groups.map((group, groupIndex) => <p key={groupIndex} className="mt-1 text-slate-300">Group {groupIndex + 1}: <span className="text-cyan-200">{group || '(unmatched)'}</span></p>) : <p className="mt-1 text-slate-600">No capture groups</p>}</div>)}</div></details>}</section>
  </main>
}
